const accs = [
  "2nd Row Left Side Seat Armrest",
  "2nd Row Right Side Seat Armrest",
  "2nd Row Seat Belt (L)",
  "2nd Row Seat Belt (R)",
  "2nd Row Seat Belt Buckle Right",
  "AUX - USB Socket",
  "Accelerator Pedal",
  "Accessory Socket (Centre Console)",
  "Accessory Socket (Dash Board)",
  "Accessory Socket (Inside Armrest)",
  "Accessory socket location (luggage compartment)",
  "Air Cleaner",
  "Airbag Label",
  "Audio System",
  "Bill - Coin Holder",
  "Brake - Clutch Fluid Reservoir",
  "Brake Pedal",
  "Centre Outlet (L)",
  "Centre Outlet (R)",
  "Child-Proof Locks (Rear L)",
  "Child-Proof Locks (Rear R)",
  "Coolant Reservoir",
  "Courtesy Lights (Duplicate)",
  "Door Locks (Driver side - O)",
  "Door Locks (Front Passenger side - I)",
  "Door Locks (Front Passenger side - O)",
  "Door Locks (Rear Left)",
  "Door Locks (Rear Right)",
  "Driver Door Switch",
  "Driver Side Defroster Outlet",
  "Driver Side Outlet",
  "Driver Side Seat Belt Buckle",
  "Engine Hood Latch",
  "Engine Oil Filler Cap",
  "Front Dome Light",
  "Second Row Seat Belt Buckle (Left)",
  "Sound System",
];

module.exports = accs;
